/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        Scanner scanner = new Scanner(System.in);
        System.out.println("Enter the image path :");
        String path = scanner.nextLine();
        System.out.println("Enter the output path :");
        boolean verfier = true;
        String output = null;
        while(verfier){
            verfier = false;
            output = scanner.nextLine();
            if(output.endsWith("/")){
                System.out.println("please enter a valid output directory without ( / ) in the end");
                verfier = true;
            }
        }

        Bitmap newimage = new Bitmap(path,output);

        boolean replay = true;
        while (replay) {
            System.out.println("=========================");
            System.out.println("Choose an option :");
            System.out.println(showMenu());
            int choice = scanner.nextInt();
            switch (choice) {
                case 1: {
                    System.out.println(showMenu());
                    break;
                }
                case 2: {
                    System.out.println("You will find the image here => app/src/main/resources :");
                    newimage.invert();
                    break;
                }
                case 3: {
                    System.out.println("You will find the image here => app/src/main/resources :");
                    newimage.blackAndWhite();
                    break;
                }
                case 4: {
                    System.out.println("Do you want it to be 1 : ClockWise OR 2 : CounterClockWise ?");
                    boolean validator = true;
                    int angle = scanner.nextInt();
                    while (validator) {
                        validator = false;
                        if (angle == 1) {
                            angle = 90;
                        } else if (angle == 2) {
                            angle = -90;
                        } else {
                            System.out.println("Enter a correct choice!");
                            angle = scanner.nextInt();
                            validator = true;
                        }
                    }
                    newimage.imageRotate(angle);
                    break;
                }
                case 5: {
                    replay = false;
                    scanner.close();
                }
            }
        }

    }

    public static String showMenu() {

        return "1: Show your options.\n2: Invert the image\n3: Apply black and white filter\n4: Rotate the image\n5: Exit the program";

    }

}